# Wave-2 "numbers" class — 33 cards. Card-script fix proposals.
#
# Verdicts: OK_AS_IS / TEXT_ONLY / SCRIPT_FIX / ENGINE_BLOCKED / UNSUPPORTED_STUB
# Doctrine: judged against CURRENT Oracle only; rules-correct > test-passing.
#   - Many "cost/number changed" reasons are TEXT-only drift: the auto= script
#     already holds the correct Oracle value; only the display text= is stale.
#     (All 6 Spike creatures, Ferrovore, Glacial Stalker, Viridian Claw,
#     Nullpriest, Charred Graverobber, Kabira Vindicator are this pattern.)
#   - A SCRIPT_FIX card may carry MORE THAN ONE dict (same "name"): one for the
#     auto=/mana= line and one for the stale text= line. Each "old" is a single
#     byte-exact line, unique within that card's block.
#   - Engine facts used: add{C} = colorless mana (borderline.txt:376 etc.);
#     damage:type:<subtype>:<zone> = dynamic count damage (borderline.txt:2027);
#     and!( tap(noevent) )! = create-then-tap idiom (borderline.txt:2932);
#     "equip-ability activation cost {1} less" is #MISSING in the corpus
#     (borderline.txt:10582); half-mana {1/2} parses only in P/T, never in a
#     payable mana cost.
#   - Web-verified current Oracle: Fallen Ferromancer {1}{R} (scryfall nph/82),
#     Assemble from Parts {1}{B}{B} (scryfall ymid/25) — script costs are the drift.

PROPOSALS = [

    # ---------------------------------------------------------------- TEXT_ONLY
    {
        "name": "Awaken the Ancient",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Enchant Mountain -- {2}: Enchanted Mountain becomes a 7/7 red Giant creature with haste. It's still a land.",
        "new": "text=Enchant Mountain -- Enchanted Mountain is a 7/7 red Giant creature with haste. It's still a land.",
        "why": "Current Oracle is a STATIC aura (Enchanted Mountain IS a 7/7 with haste), no {2} activation. auto=transforms((Giant Creature,setpower=7,settoughness=7,red,haste)) is already the correct continuous transform; only text= carries the errata'd-away {2} activation cost.",
        "probe": "Attach aura to a Mountain; assert it is a 7/7 red Giant with haste and still a land, with no activation needed.",
    },
    {
        "name": "Caller of the Hunt",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=As Caller of the Hunt enters, choose a creature type. -- Caller of the Hunt's power and toughness are each equal to the number of creatures of the chosen type on the battlefield.",
        "new": "text=As an additional cost to cast this spell, choose a creature type. -- Caller of the Hunt's power and toughness are each equal to the number of creatures of the chosen type on the battlefield.",
        "why": "Only timing wording drifted. auto=chooseatype + CDA counter already delivers the functional effect (choose type, P/T = count of that type). Oracle's 'additional cost to cast' vs the text's 'as it enters' is a seam nuance the engine models via chooseatype; effect is faithful.",
        "probe": "Cast with two Goblins in play, choose Goblin; assert Caller is 3/3 (2 Goblins + itself).",
    },
    {
        "name": "Ferrovore",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text={R}, sacrifice an artifact: Ferrovore gets +3/+3 until end of turn.",
        "new": "text={R}, Sacrifice an artifact: Ferrovore gets +3/+0 until end of turn.",
        "why": "auto={R}{S(artifact|myBattlefield)}:3/0 already gives +3/+0 per Oracle. text= wrongly shows +3/+3.",
        "probe": "Activate; assert Ferrovore is 5/2 (base 2/2 +3/+0) until end of turn.",
    },
    {
        "name": "Glacial Stalker",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Morph {2}{W} (You may cast this face down as a 2/2 creature for {3}. Turn it face up any time for its morph cost.)",
        "new": "text=Morph {4}{U} (You may cast this card face down as a 2/2 creature for {3}. Turn it face up any time for its morph cost.)",
        "why": "autofacedown={4}{U}:morph already matches Oracle Morph {4}{U}. text= shows a wrong {2}{W} morph cost (wrong color entirely).",
        "probe": "Cast face down for {3}; unmorph paying {4}{U}; assert it flips to the 4/5 Elemental.",
    },
    {
        "name": "Kabira Vindicator",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Level up {2}{W} -- [Level 2-4] Other creatures you control get +1/+1. (3/6) -- [Level 5+] Other creatures you control get +1/+1. (4/8)",
        "new": "text=Level up {2}{W} -- [Level 2-4] Other creatures you control get +1/+1. (3/6) -- [Level 5+] Other creatures you control get +2/+2. (4/8)",
        "why": "Script is correct via THRESHOLD STACKING: the level-2 lord (+1/+1) and level-5 lord (+1/+1) both apply at level 5+, summing to +2/+2 (and its own 2/4 base +1/+2 +1/+2 = 4/8). Only the text= L5+ line wrongly reads +1/+1.",
        "probe": "Add 5 level counters; assert an OTHER creature you control gets +2/+2 and Kabira is 4/8.",
    },
    {
        "name": "Leaping Master",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Leaping Master gains flying until end of turn.",
        "new": "text={2}{W}: Leaping Master gains flying until end of turn.",
        "why": "auto={2}{W}:flying ueot already carries the {2}{W} activation cost. text= omits the cost, reading as a static/free grant.",
        "probe": "Activate for {2}{W}; assert Leaping Master has flying until end of turn.",
    },
    {
        "name": "Spike Colony",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Spike Colony enters with a +1/+1 counter on it. -- {2}, Remove a +1/+1 counter from Spike Colony: Put a +1/+1 counter on target creature.",
        "new": "text=Spike Colony enters with four +1/+1 counters on it. -- {2}, Remove a +1/+1 counter from Spike Colony: Put a +1/+1 counter on target creature.",
        "why": "auto=counter(1/1,4) already enters with four counters per Oracle. text= boilerplate says 'a +1/+1 counter'.",
        "probe": "Put into play; assert Spike Colony is 4/4 (four +1/+1 counters).",
    },
    {
        "name": "Spike Breeder",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Spike Breeder enters with a +1/+1 counter on it. -- {2}, Remove a +1/+1 counter from Spike Breeder: Put a +1/+1 counter on target creature. -- {2}, Remove a +1/+1 counter from Spike Breeder: Put a 1/1 green Spike creature token onto the battlefield.",
        "new": "text=Spike Breeder enters with three +1/+1 counters on it. -- {2}, Remove a +1/+1 counter from Spike Breeder: Put a +1/+1 counter on target creature. -- {2}, Remove a +1/+1 counter from Spike Breeder: Create a 1/1 green Spike creature token.",
        "why": "auto=counter(1/1,3) already enters with three per Oracle. text= says 'a +1/+1 counter' and uses legacy 'onto the battlefield' phrasing.",
        "probe": "Put into play; assert Spike Breeder is 3/3.",
    },
    {
        "name": "Spike Soldier",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Spike Soldier enters with a +1/+1 counter on it. -- {2}, Remove a +1/+1 counter from Spike Soldier: Put a +1/+1 counter on target creature. -- {2}, Remove a +1/+1 counter from Spike Soldier: Spike Soldier gets +2/+2 until end of turn.",
        "new": "text=Spike Soldier enters with three +1/+1 counters on it. -- {2}, Remove a +1/+1 counter from Spike Soldier: Put a +1/+1 counter on target creature. -- Remove a +1/+1 counter from Spike Soldier: Spike Soldier gets +2/+2 until end of turn.",
        "why": "auto=counter(1/1,3) (three per Oracle) and auto={C(1/1,-1)}:2/2 (pump has NO {2}, just remove-a-counter) are both correct. text= wrongly says 'a counter' AND prefixes the pump with a spurious {2}.",
        "probe": "Put into play (assert 3/3); activate pump paying only a counter (no mana); assert +2/+2.",
    },
    {
        "name": "Spike Feeder",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Spike Feeder enters with a +1/+1 counter on it. -- {2}, Remove a +1/+1 counter from Spike Feeder: Put a +1/+1 counter on target creature. -- {2}, Remove a +1/+1 counter from Spike Feeder: You gain 2 life.",
        "new": "text=Spike Feeder enters with two +1/+1 counters on it. -- {2}, Remove a +1/+1 counter from Spike Feeder: Put a +1/+1 counter on target creature. -- Remove a +1/+1 counter from Spike Feeder: You gain 2 life.",
        "why": "auto=counter(1/1,2) (two per Oracle) and auto={C(1/1,-1)}:life:2 (gain-life costs only a counter, no {2}) are correct. text= wrongly says 'a counter' and prefixes the life gain with {2}.",
        "probe": "Put into play (assert 2/2); activate life gain paying only a counter; assert +2 life.",
    },
    {
        "name": "Spike Worker",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Spike Worker enters with a +1/+1 counter on it. -- {2}, Remove a +1/+1 counter from Spike Worker: Put a +1/+1 counter on target creature.",
        "new": "text=Spike Worker enters with two +1/+1 counters on it. -- {2}, Remove a +1/+1 counter from Spike Worker: Put a +1/+1 counter on target creature.",
        "why": "auto=counter(1/1,2) already enters with two per Oracle. text= boilerplate says 'a +1/+1 counter'.",
        "probe": "Put into play; assert Spike Worker is 2/2.",
    },
    {
        "name": "Spike Hatcher",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Spike Hatcher enters with a +1/+1 counter on it. -- {2}, Remove a +1/+1 counter from Spike Hatcher: Put a +1/+1 counter on target creature. -- {2}, Remove a +1/+1 counter from Spike Hatcher: Regenerate Spike Hatcher.",
        "new": "text=Spike Hatcher enters with six +1/+1 counters on it. -- {2}, Remove a +1/+1 counter from Spike Hatcher: Put a +1/+1 counter on target creature. -- {1}, Remove a +1/+1 counter from Spike Hatcher: Regenerate Spike Hatcher.",
        "why": "auto=counter(1/1,6) (six per Oracle) and auto={1}{C(1/1,-1)}:regenerate (regen cost {1}, not {2}) are both correct. text= wrongly says 'a counter' and shows {2} for regenerate.",
        "probe": "Put into play (assert 6/6); regenerate paying {1}+counter after lethal.",
    },
    {
        "name": "Triassic Egg",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text={3}{T}: Put a hatchling counter on Triassic Egg. -- Remove two hatchling counters from Triassic Egg, Sacrifice Triassic Egg: You may put a creature card from your hand or graveyard onto the battlefield.",
        "new": "text={3}, {T}: Put a hatchling counter on Triassic Egg. -- Sacrifice Triassic Egg: Choose one -- Activate only if there are two or more hatchling counters on Triassic Egg. -- * You may put a creature card from your hand onto the battlefield. -- * Return target creature card from your graveyard to the battlefield.",
        "why": "Script is functionally faithful: {C(0/0,-2,Hatchling)}{S} (remove 2 + sacrifice) has the SAME outcome as the current Oracle's 'Sacrifice, activate only if 2+ counters' — the egg is gone either way, so removing-2-as-cost is just modeling the 2-counter gate at a different seam (per the wave brief's cost caution). target(creature|myhand,mygraveyard) -> moveTo(battlefield) already gives the 'choose one' hand-or-graveyard put. Only the text= reflects the pre-errata (non-modal) wording.",
        "probe": "Give it 2 hatchling counters; sacrifice; assert a creature from hand OR graveyard enters the battlefield.",
    },
    {
        "name": "Viridian Claw",
        "file": "mtg.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Equipped creature gets +1/+0 and has first strike. -- Equip {2}",
        "new": "text=Equipped creature gets +1/+0 and has first strike. -- Equip {1}",
        "why": "auto={1}:equip already matches Oracle Equip {1}. text= shows a stale Equip {2}.",
        "probe": "Equip paying {1}; assert equipped creature gets +1/+0 and first strike.",
    },
    {
        "name": "Brightcap Badger // Fungus Frolic",
        "file": "borderline.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Each Fungus and Saproling you control has \"{T}: Add {G}.\" -- At the beginning of your end step, create a 1/1 green Saproling creature token.",
        "new": "text=Each Fungus and Saproling you control has \"{T}: Add {G}.\" -- At the beginning of your end step, create a 1/1 green Saproling creature token. -- Create two 1/1 green Saproling creature tokens. (Then exile this card. You may cast the creature later from exile.)",
        "why": "The adventure half IS scripted (abilities=adventure, other={2}{G} name(Adventure), auto=alternative _SAPROLINGTOKEN_*2 = two Saprolings). Only the text= omits the Fungus Frolic adventure clause.",
        "probe": "Cast the adventure Fungus Frolic for {2}{G}; assert two 1/1 green Saprolings and the card is exiled castable as the creature.",
    },
    {
        "name": "Charred Graverobber",
        "file": "borderline.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=When Charred Graverobber enters, return target outlaw card from your graveyard to your hand. -- Escape-{3}{B}, Exile four other cards from your graveyard. (You may cast this card from your graveyard for its escape cost.) -- Charred Graverobber escapes with a +1/+1 counter on it.",
        "new": "text=When Charred Graverobber enters, return target outlaw card from your graveyard to your hand. -- Escape-{3}{B}{B}, Exile four other cards from your graveyard. (You may cast this card from your graveyard for its escape cost.) -- Charred Graverobber escapes with a +1/+1 counter on it.",
        "why": "retrace={3}{B}{B}{E...}x4 already holds the correct {3}{B}{B} escape cost. text= shows a stale {3}{B}.",
        "probe": "Cast from graveyard paying {3}{B}{B} + exile 4 cards; assert it escapes with a +1/+1 counter.",
    },
    {
        "name": "Nullpriest of Oblivion",
        "file": "borderline.txt",
        "verdict": "TEXT_ONLY",
        "old": "text=Kicker {4}{B} -- Menace, lifelink -- When Nullpriest of Oblivion enters, if it was kicked, return target creature card from your graveyard to the battlefield.",
        "new": "text=Kicker {3}{B} -- Menace, lifelink -- When Nullpriest of Oblivion enters, if it was kicked, return target creature card from your graveyard to the battlefield.",
        "why": "kicker={3}{B} already matches Oracle. text= shows a stale Kicker {4}{B}.",
        "probe": "Cast kicked for {1}{B} + {3}{B}; assert a creature returns from graveyard to battlefield.",
    },

    # ---------------------------------------------------------------- SCRIPT_FIX
    {
        "name": "Contested Cliffs",
        "file": "mtg.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto={T}:add{1}",
        "new": "auto={T}:add{C}",
        "why": "Oracle first ability is '{T}: Add {C}' (colorless), not generic {1}. add{C} produces colorless mana (borderline.txt:376). NOTE (out of numbers-scope, left as-is): the fight's second target uses bare target(creature) rather than opponent-restricted; the Oracle says 'a creature an opponent controls'.",
        "probe": "Tap for mana; assert one colorless {C} added to pool.",
    },
    {
        "name": "Contested Cliffs",
        "file": "mtg.txt",
        "verdict": "SCRIPT_FIX",
        "old": "text={T}: Add {1}. -- {R}{G}, {T}: Choose target Beast creature you control and target creature an opponent controls. Those creatures fight each other. (Each deals damage equal to its power to the other.)",
        "new": "text={T}: Add {C}. -- {R}{G}, {T}: Target Beast creature you control fights target creature an opponent controls. (Each deals damage equal to its power to the other.)",
        "why": "text= refresh accompanying the add{1}->add{C} fix; also restores Oracle fight wording.",
        "probe": "(display only)",
    },
    {
        "name": "Fallen Ferromancer",
        "file": "mtg.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto={2}{R}{T}:damage:1 target(anytarget)",
        "new": "auto={1}{R}{T}:damage:1 target(anytarget)",
        "why": "Web-verified current Oracle (scryfall nph/82): '{1}{R}, {T}: deals 1 damage to any target.' Script holds the drifted {2}{R}. (Not wrong-way-round: confirmed against live Oracle, not the judge reason.)",
        "probe": "Activate paying {1}{R}+tap targeting a player; assert 1 damage (a poison counter via infect).",
    },
    {
        "name": "Fallen Ferromancer",
        "file": "mtg.txt",
        "verdict": "SCRIPT_FIX",
        "old": "text=Infect -- {2}{R}, {T}: Fallen Ferromancer deals 1 damage to any target.",
        "new": "text=Infect -- {1}{R}, {T}: Fallen Ferromancer deals 1 damage to any target.",
        "why": "text= refresh accompanying the {2}{R}->{1}{R} cost fix.",
        "probe": "(display only)",
    },
    {
        "name": "Mana Seism",
        "file": "mtg.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto=sacrifice && add{1}",
        "new": "auto=sacrifice && add{C}",
        "why": "Oracle: 'Sacrifice any number of lands, then add that much {C}' — colorless, not generic {1}. Same per-target construct, only the mana color changes.",
        "probe": "Sacrifice 2 lands; assert {C}{C} (2 colorless) added to pool.",
    },
    {
        "name": "Mana Seism",
        "file": "mtg.txt",
        "verdict": "SCRIPT_FIX",
        "old": "text=Sacrifice any number of lands. Add {1} for each land sacrificed this way.",
        "new": "text=Sacrifice any number of lands, then add that much {C}.",
        "why": "text= refresh accompanying add{1}->add{C}.",
        "probe": "(display only)",
    },
    {
        "name": "Pilfered Plans",
        "file": "mtg.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto=deplete:3",
        "new": "auto=deplete:2",
        "why": "Oracle: 'Target player mills two cards.' deplete = mill (AADepleter); script mills 3. Draw leg (auto=draw:2 controller) already correct.",
        "probe": "Target a player with a stocked library; assert exactly 2 cards milled and controller draws 2.",
    },
    {
        "name": "Pilfered Plans",
        "file": "mtg.txt",
        "verdict": "SCRIPT_FIX",
        "old": "text=Target player mills three cards. -- Draw two cards.",
        "new": "text=Target player mills two cards. -- Draw two cards.",
        "why": "text= refresh accompanying deplete:3->deplete:2.",
        "probe": "(display only)",
    },
    {
        "name": "Bounty of the Luxa",
        "file": "borderline.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto=@each my firstmain restriction{compare(hascntflood)~morethan~0}:name(Remove all counters and add mana) name(Remove all counters and add mana) removeallcounters(0/0,1,flood) && add{1}{G}{U} controller",
        "new": "auto=@each my firstmain restriction{compare(hascntflood)~morethan~0}:name(Remove all counters and add mana) name(Remove all counters and add mana) removeallcounters(0/0,1,flood) && add{1}{G}{U} controller".replace("add{1}{G}{U}", "add{C}{G}{U}"),
        "why": "Oracle: 'Otherwise, add {C}{G}{U}.' — the '{1}' generic should be colorless '{C}'. Only the mana color changes.",
        "probe": "With a flood counter present, pass first main; assert {C}{G}{U} added (colorless, not generic).",
    },
    {
        "name": "Bounty of the Luxa",
        "file": "borderline.txt",
        "verdict": "SCRIPT_FIX",
        "old": "text=At the beginning of your precombat main phase, remove all flood counters from Bounty of the Luxa. If no counters were removed this way, put a flood counter on Bounty of the Luxa and draw a card. Otherwise, add {1}{G}{U}.",
        "new": "text=At the beginning of your first main phase, remove all flood counters from Bounty of the Luxa. If no counters were removed this way, put a flood counter on Bounty of the Luxa and draw a card. Otherwise, add {C}{G}{U}.",
        "why": "text= refresh accompanying add{1}{G}{U}->add{C}{G}{U}.",
        "probe": "(display only)",
    },
    {
        "name": "Assemble from Parts",
        "file": "borderline.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto=emblem transforms((,newability[lord(*[counter{0/0.1.PerpetualAssemble}]|graveyard) transforms((,newability[{3}{B}:name(Shuffle and copy) moveto(myexile) and!( moveto(mylibrary) and!( clone and!( transforms((Zombie,black,setpower=4,settoughness=4,newability[shuffle])) forever )! )! )! asSorcery]))])) forever dontremove",
        "new": "auto=emblem transforms((,newability[lord(*[counter{0/0.1.PerpetualAssemble}]|graveyard) transforms((,newability[{1}{B}{B}:name(Shuffle and copy) moveto(myexile) and!( moveto(mylibrary) and!( clone and!( transforms((Zombie,black,setpower=4,settoughness=4,newability[shuffle])) forever )! )! )! asSorcery]))])) forever dontremove",
        "why": "Web-verified current Oracle (scryfall ymid/25): the perpetually-granted ability costs '{1}{B}{B}', not the script's {3}{B}. Same effect shape (exile->shuffle->4/4 Zombie copy, sorcery-speed); only the activation cost of the granted ability changes.",
        "probe": "Target a creature card in graveyard; assert it gains the ability and activating it costs {1}{B}{B}.",
    },
    {
        "name": "Assemble from Parts",
        "file": "borderline.txt",
        "verdict": "SCRIPT_FIX",
        "old": "text=Target creature card in your graveyard perpetually gains \"{3}{B}, Exile this card from your graveyard: Shuffle it into your library. Create a token that's a copy of it, except it's a 4/4 black Zombie in addition to its other types. Activate only as a sorcery.\"",
        "new": "text=Target creature card in your graveyard perpetually gains \"{1}{B}{B}, Exile this card from your graveyard: Shuffle it into its owner's library. Create a token that's a copy of it, except it's a 4/4 black Zombie in addition to its other types. Activate only as a sorcery.\"",
        "why": "text= refresh accompanying {3}{B}->{1}{B}{B} (and 'its owner's library' per Oracle).",
        "probe": "(display only)",
    },
    {
        "name": "Garruk, Wrath of the Wilds",
        "file": "planeswalkers.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto={C(0/0,-5,Loyalty)}:name(-3: Your creatures get 3/3) all(creature|myBattlefield) transforms((,newability[3/3],trample)) ueot",
        "new": "auto={C(0/0,-6,Loyalty)}:name(-6: Your creatures get +3/+3 and trample) all(creature|myBattlefield) transforms((,newability[3/3],trample)) ueot",
        "why": "Oracle ultimate is -6 ('creatures you control get +3/+3 and gain trample'), not -5. Loyalty cost fixed -5->-6; the stale 'name(-3: ...)' label corrected to -6 (the +3/+3 UEOT effect is already correct).",
        "probe": "Set Garruk to 6 loyalty; activate; assert your creatures get +3/+3 and trample UEOT and loyalty is 0.",
    },
    {
        "name": "Garruk, Wrath of the Wilds",
        "file": "planeswalkers.txt",
        "verdict": "SCRIPT_FIX",
        "old": "text=+1: Choose a creature card in your hand. it perpetually gets +1/+1 and perpetually gains \"This spell costs {1} less to cast.\" -- -1: Draft a card from Garruk, Wrath of the Wild's spellbook and put it onto the battlefield. -- -5: Until end of turn, creatures you control get +3/+3 and gain trample.",
        "new": "text=+1: Choose a creature card in your hand. It perpetually gets +1/+1 and perpetually gains \"This spell costs {1} less to cast.\" -- -1: Draft a card from Garruk, Wrath of the Wilds's spellbook and put it onto the battlefield. -- -6: Until end of turn, creatures you control get +3/+3 and gain trample.",
        "why": "text= refresh accompanying the -5->-6 ultimate cost fix.",
        "probe": "(display only)",
    },
    {
        "name": "Tibalt, Wicked Tormentor",
        "file": "planeswalkers.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto={C(0/0,1,Loyalty)}:name(+1: Damage opponent creature or planeswalker) target(*[creature;planeswalker]|opponentbattlefield) transforms((,newability[choice name(Damage target) damage:3],newability[choice name(Damage controller) damage:3 controller && ability$!may name(Discard and draw) name(Discard and draw) target(*|myhand) reject and!( draw:1 controller )! !$ opponent])) oneshot",
        "new": "auto={C(0/0,1,Loyalty)}:name(+1: Damage opponent creature or planeswalker) target(*[creature;planeswalker]|opponentbattlefield) transforms((,newability[choice name(Damage target) damage:4],newability[choice name(Damage controller) damage:4 controller && ability$!may name(Discard and draw) name(Discard and draw) target(*|myhand) reject and!( draw:1 controller )! !$ opponent])) oneshot",
        "why": "Oracle second +1 deals 4 damage (both to the creature/pw and, alternatively, to its controller); script uses 3. Both damage:3 on this line -> damage:4. Pure number change, no structural edit.",
        "probe": "Activate +1 damage vs an opponent creature; assert 4 damage dealt.",
    },
    {
        "name": "Tibalt, Wicked Tormentor",
        "file": "planeswalkers.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto={C(0/0,1,Loyalty)}:name(+1: Damage your creature or planeswalker) target(*[creature;planeswalker]|mybattlefield) transforms((,newability[choice name(Damage target) damage:3],newability[choice name(Damage controller) damage:3 controller && ability$!may name(Discard and draw) name(Discard and draw) target(*|myhand) reject and!( draw:1 controller )! !$ controller])) oneshot",
        "new": "auto={C(0/0,1,Loyalty)}:name(+1: Damage your creature or planeswalker) target(*[creature;planeswalker]|mybattlefield) transforms((,newability[choice name(Damage target) damage:4],newability[choice name(Damage controller) damage:4 controller && ability$!may name(Discard and draw) name(Discard and draw) target(*|myhand) reject and!( draw:1 controller )! !$ controller])) oneshot",
        "why": "Companion line (targets your own creature/pw). Same 3->4 damage fix on both damage:3.",
        "probe": "Activate +1 damage vs your own creature; assert 4 damage.",
    },
    {
        "name": "Tibalt, Wicked Tormentor",
        "file": "planeswalkers.txt",
        "verdict": "SCRIPT_FIX",
        "old": "text=+1: Add {R}{R}. Draft a card from Tibalt, Wicked Tormenter's spellbook, then exile it. Until end of turn, you may cast that card. -- +1: Tibalt, Wicked Tormenter deals 3 damage to target creature or planeswalker unless its controller has Tibalt deal 3 damage to them. If they do, you may discard a card. If you do, draw card. -- -X: Create X 1/1 red Devil creature tokens with \"When this creature dies, it deals 1 damage to any target.\"",
        "new": "text=+1: Add {R}{R}. Draft a card from Tibalt, Wicked Tormentor's spellbook, then exile it. Until end of turn, you may cast that card. -- +1: Tibalt, Wicked Tormentor deals 4 damage to target creature or planeswalker unless its controller has Tibalt deal 4 damage to them. If they do, you may discard a card. If you do, draw a card. -- -X: Create X 1/1 red Devil creature tokens with \"When this creature dies, it deals 1 damage to any target.\"",
        "why": "text= refresh accompanying the 3->4 damage fix (also corrects 'Tormenter'->'Tormentor').",
        "probe": "(display only)",
    },
    {
        "name": "Soulhunter Rakshasa",
        "file": "borderline.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto=damage:5 target(opponent)",
        "new": "auto=damage:type:swamp:mybattlefield target(opponent)",
        "why": "Oracle ETB deals '1 damage to target opponent for each Swamp you control', not a flat 5 (the 5 was a fixed-value placeholder). damage:type:<subtype>:<zone> is the dynamic-count damage construct (borderline.txt:2027); keeping target(opponent) unchanged means NO new chooser is introduced (safe vs the trigger-payload-fizzle engine gap). RESIDUAL: the 'if you cast it from your hand' condition has no card-script construct (no castfromhand token exists), so the card will also deal damage when put into play by other means (e.g. reanimation) — minor edge, the per-Swamp scaling is the load-bearing Oracle fidelity.",
        "probe": "Cast from hand with 3 Swamps in play; assert 3 damage to the opponent. Then with 0 Swamps assert 0.",
    },
    {
        "name": "Soulhunter Rakshasa",
        "file": "borderline.txt",
        "verdict": "SCRIPT_FIX",
        "old": "text=Soulhunter Rakshasa can't block. -- When Soulhunter Rakshasa enters, it deals 5 damage to target opponent.",
        "new": "text=Soulhunter Rakshasa can't block. -- When Soulhunter Rakshasa enters, if you cast it from your hand, it deals 1 damage to target opponent for each Swamp you control.",
        "why": "text= refresh to Oracle accompanying the flat-5 -> per-Swamp fix (displays the from-hand clause even though the engine can't gate on it — see auto residual note).",
        "probe": "(display only)",
    },
    {
        "name": "Old-Growth Troll",
        "file": "borderline.txt",
        "verdict": "SCRIPT_FIX",
        "old": "auto=alternative name(Enchant Forest) name(Enchant Forest) target(land[forest]|mybattlefield) transforms((,newability[counter(0/0.1.TrollEffect)],newability[this(counter{0/0.1.TrollEffect}>0) {T}:add{G}{G}],newability[this(counter{0/0.1.TrollEffect}>0) {1}{T}{S}:token(Troll^Creature Troll Warrior^4/4^green^trample)])) forever",
        "new": "auto=alternative name(Enchant Forest) name(Enchant Forest) target(land[forest]|mybattlefield) transforms((,newability[counter(0/0.1.TrollEffect)],newability[this(counter{0/0.1.TrollEffect}>0) {T}:add{G}{G}],newability[this(counter{0/0.1.TrollEffect}>0) {1}{T}{S}:token(Troll^Creature Troll Warrior^4/4^green^trample) and!( tap(noevent) )!])) forever",
        "why": "Oracle: '...Create a TAPPED 4/4 green Troll Warrior creature token with trample.' Script creates it untapped (real difference: a tapped token can't block until it untaps). 'and!( tap(noevent) )!' is the corpus create-then-tap idiom (borderline.txt:2932). RISK: this attaches and! inside a nested newability[...] within transforms((; PROBE-VERIFY the and! actually taps the created token before shipping — if it doesn't attach in this nesting, the token may need to be created via a separate seam.",
        "probe": "Play the aura on a Forest, activate {1}{T}+sac; assert the created Troll Warrior enters TAPPED. Run the FULL suite (nested and! attachment is unverified).",
    },
    {
        "name": "Old-Growth Troll",
        "file": "borderline.txt",
        "verdict": "SCRIPT_FIX",
        "old": "and \"{1}, {T}, Sacrifice this land: Create a 4/4 green Troll Warrior creature token with trample.\"",
        "new": "and \"{1}, {T}, Sacrifice this land: Create a tapped 4/4 green Troll Warrior creature token with trample.\"",
        "why": "text= refresh accompanying the tapped-token fix (partial-line, unique within the block).",
        "probe": "(display only)",
    },

    # -------------------------------------------------------------- OK_AS_IS
    {
        "name": "Wood Elemental",
        "file": "mtg.txt",
        "verdict": "OK_AS_IS",
        "why": "Oracle: 'P/T each equal to the number of Forests sacrificed AS IT ENTERED' — a value FIXED at entry, not a live CDA. auto=... sacrifice && counter(1/1) all(this) places that many +1/+1 counters at entry, which is the faithful fixed-at-entry model (a live '*' CDA would wrongly re-count as Forests later change). text= honestly describes the counter mechanism; refreshing it to '*/*' would misrepresent the displayed 0/0+counters. No change.",
        "probe": "Enter sacrificing 3 untapped Forests; assert Wood Elemental is 3/3 and stays 3/3 if a Forest later leaves.",
    },

    # -------------------------------------------------------------- ENGINE_BLOCKED
    {
        "name": "Arms Scavenger",
        "file": "borderline.txt",
        "verdict": "ENGINE_BLOCKED",
        "why": "The spellbook-draft upkeep ability is fully scripted and correct. The MISSING clause is the static 'Equip abilities you activate cost {1} less to activate' — there is NO card-script construct for reducing EQUIP-ABILITY ACTIVATION cost (altercost/lord reduces equip-SPELL casting cost only). The corpus itself marks this exact shape #MISSING (borderline.txt:10582, and Bladegraft Aspirant 10558). Needs an engine primitive (ability-type-filtered activation-cost reducer); do not bend a shared primitive for it.",
        "probe": "N/A until engine support exists. Regression-guard: assert the upkeep draft ability still fires.",
    },
    {
        "name": "Flaccify",
        "file": "borderline.txt",
        "verdict": "ENGINE_BLOCKED",
        "why": "Oracle: 'Counter target spell unless its controller pays {3}{1/2}.' The half-mana symbol {1/2} parses ONLY in power/toughness fields (unsupported.txt) and never appears in a payable mana cost anywhere in the corpus; pay[[{3}{1/2}]] is not a supported cost. Script pays {3} (missing the half). Faithful fix needs half-mana cost support in ManaCost/ExtraCost. Low priority (silver-bordered Unglued card).",
        "probe": "N/A until half-mana costs are supported.",
    },
    {
        "name": "Liliana of the Veil",
        "file": "planeswalkers.txt",
        "verdict": "ENGINE_BLOCKED",
        "why": "Oracle -6: 'Separate ALL permanents target player controls into two piles. That player sacrifices all permanents in the pile of their choice.' This two-pile interactive separation (Fact-or-Fiction shaped) has no card-script construct. The current script approximates it as 'sacrifice half rounded up' (<halfuptype:*...>), which is a deliberate simplification but NOT rules-correct (piles let the player keep a chosen subset; totals differ). Needs an engine pile-division primitive. +1 (each player discards) and -2 (target player sacrifices a creature) are fine.",
        "probe": "N/A until pile-separation is supported.",
    },

    # -------------------------------------------------------------- UNSUPPORTED_STUB
    {
        "name": "Cheap Ass",
        "file": "unsupported.txt",
        "verdict": "UNSUPPORTED_STUB",
        "why": "No auto=/mana-reduction script (text-only stub in unsupported.txt). Oracle 'Spells you cast cost {1/2} less to cast' would also require half-mana cost-reduction support, which does not exist. Nothing to fix without building the card.",
        "probe": "N/A (stub).",
    },
    {
        "name": "Old Fogey",
        "file": "unsupported.txt",
        "verdict": "UNSUPPORTED_STUB",
        "why": "No auto= script (text-only stub in unsupported.txt). The judged drifts (cumulative upkeep {1} vs echo {G}{G}) are moot — the card implements none of its ~10 keyword abilities (phasing, cumulative upkeep, echo, fading, banding, flanking, rampage, plainswalk, protection). A silver-age joke card; not buildable without broad engine support.",
        "probe": "N/A (stub).",
    },

]
